<?php

use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function recaptcha_form_alter(&$form, &$form_state, $form_id) {
  $user = \Drupal::currentUser();
  if (!$user->hasPermission('skip recaptcha')) {
    $config = \Drupal::config('recaptcha.settings');
    $form_ids = $config->get('form_ids');
    if (in_array($form_id, $form_ids)) {
      $form['recaptcha'] = [
        '#type' => 'recaptcha',
        '#weight' => 100,
      ];
      $form['actions']['#weight'] = $form['recaptcha']['#weight'] + 1;
    }
  }
}

/**
 * Implements hook_theme().
 */
function recaptcha_theme($existing, $type, $theme, $path) {
  return [
    'recaptcha' => ['variables' => ['site_key' => NULL]],
  ];
}

/**
 * Theme function for the ["#type" => "recaptcha"] elements.
 */
function theme_recaptcha($vars) {
  return '<div class="g-recaptcha" data-sitekey="' . $vars['site_key'] . '"></div>';
}

/**
 * Implements hook_element_info().
 */
function recaptcha_element_info() {
  return [
    'recaptcha' => [
      '#input' => FALSE,
      '#pre_render' => [['Drupal\recaptcha\Element\Recaptcha', 'preRenderRecaptcha']],
      '#element_validate' => [['Drupal\recaptcha\Element\Recaptcha', 'validateRecaptcha']],
      '#theme' => 'recaptcha',
    ],
  ];
}
