<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function recaptcha_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // TODO make forms configurable.
  if ($form_id === 'comment_comment_form') {
    $form['recaptcha'] = [
      '#type' => 'recaptcha',
      '#weight' => 100,
    ];
  }
}

/**
 *  Implements hook_theme().
 */
function recaptcha_theme($existing, $type, $theme, $path) {
  return [
    'recaptcha' => ['variables' => ['site_key' => NULL]],
  ];
}
